#докер файл начинается с версии
#указываем версию 2.1 и выше иначе механизм healthckeck не будет работать
version: '2.1'
#раздел, в котором будут описаны сервисы
services:
#указываем первый сервис php.Название само по себе не важно. Можно назвать как удобно. Важно  , чтобы это было понятно.Понятное назание сервиса помогает определить его роль.
#Мы собираемся собрать два контейнера
#Первый контейнер будет содержать среду разработки php.
  php:
#Задаем путь к файлу с помощью build
    build:
       context: php/
#Указываем имя докер-файла в каталоге php
       dockerfile: dockerfile
#Задаем имя контейнера, чтобы проще было работать.
    container_name: php
#указываем порт 
    ports:
      - "8280:80"
#Далее идет значение depends_on - Позволяет указывать, должен ли сервис , прежде чем запускаться, ждать.
    depends_on:
#Указываем сервис redis 
      redis:
$Выбираем механизм healthy
        condition: service_healthy
$далее указываем на новый сервис
  redis:
#Задаем путь к файлу с помощью build. Далее строки аналогичны:29-11; 30-12; 31-14; 32-16
    build:
       context: redis/
       dockerfile: dockerfile
    container_name: redis
#Выбираем механизм healtcheck. Необходим для мониторинга сервиса. В данном случаи используем ping
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
#Задаем интервал 
      interval: 10s

